# Generated by Django 2.1.2 on 2019-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table='list',
        ),
    ]
