# Generated by Django 2.1.2 on 2019-05-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_auto_20190519_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table='List',
        ),
    ]
